linters:
  enable:
  - errcheck
  - govet
  - ineffassign
  - staticcheck
  - unused
  - bodyclose
  - gosec
  - misspell
  disable:
  - funlen
  - gocyclo
  - lll

linters-settings:
  errcheck:
    # Exclude legacy server code from errcheck
    exclude-functions:
    - (*github.com/go-kit/log.Logger).Log
    - (github.com/go-kit/log.Logger).Log

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
  - "test"
  - "tests"
  exclude-files:
  - ".*_test\\.go"
  exclude-rules:
  - path: server/
    linters:
    - errcheck
    - gosec
  - path: tools/
    linters:
    - errcheck
    - gosec

run:
  timeout: 5m
