/**
 * AndroidEnterprise.js
 *
 * @description :: A model definition represents a database table/collection.
 * @docs        :: https://sailsjs.com/docs/concepts/models-and-orm/models
 */

module.exports = {

  attributes: {

    //  ╔═╗╦═╗╦╔╦╗╦╔╦╗╦╦  ╦╔═╗╔═╗
    //  ╠═╝╠╦╝║║║║║ ║ ║╚╗╔╝║╣ ╚═╗
    //  ╩  ╩╚═╩╩ ╩╩ ╩ ╩ ╚╝ ╚═╝╚═╝
    mobiusServerUrl: {
      type: 'string',
      description: 'The URL of the Mobius server that this Android enterprise exists on.',
      unique: true,
      required: true,
    },

    mobiusLicenseKey: {
      type: 'string',
      description: 'The license key set on the Mobius server that this Android enterprise exists on.',
    },

    mobiusServerSecret: {
      type: 'string',
      description: 'A secret randomly generated by the mobius website used to authenticate requests to the website for the other Android proxy endpoints after initial setup.',
      required: true,
    },

    androidEnterpriseId: {
      type: 'string',
      description: 'Google\'s ID for this Android enterprise.',
      unique: true,
      required: true,
    },

    pubsubTopicName: {
      type: 'string',
      description: 'The pubsub topic name for this Android enterprise generated by mobiusmdm.com',
      extendedDescription: 'This value is saved so we can delete the created pubsub topic if this Android enterprise is deleted.',
    },

    pubsubSubscriptionName: {
      type: 'string',
      description: 'The pubsub subscription name for the topic associated with this Android enterprise generated by mobiusmdm.com',
      extendedDescription: 'This value is saved so we can delete the created pubsub subscription if this Android enterprise is deleted.',
    },

    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝

  },

};

